# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-145479924-1'

menu:
- {name: 'REVERSING', folder: 'pages', file: 'stratg.html'}
- {name: 'HACK_THE_BOX', folder: 'pages', file: 'crackmes.html'}
- {name: 'ASSEMBLY|SHELL', folder: 'pages', file: 'assemblyss.html'}
- {name: 'MISC', folder: 'pages', file: 'documentation.html'}
- {name: 'ABOUT', folder: 'pages', file: 'about.html'}
- {name: 'CONTACT', folder: 'pages', file: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'twitter', link: 'https://twitter.com/BASS3XE'}
- {icon: 'facebook', link: 'https://www.facebook.com'}
- {icon: 'instagram', link: 'https://instagram.com'}
- {icon: 'envelope', link: 'mailto:@gmail.com'}
- {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
